class AppSecrets {
  static const String supabaseUrl= 'https://aclhbsmxyeuomqdowsle.supabase.co';
  static const String supabaseAnnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbGhic214eWV1b21xZG93c2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTg2NzQsImV4cCI6MjA1MDE5NDY3NH0.Uk21iAyuhXQS9jnC5RNtOKFzX4IkKuZfXkjsirMQYes';
}